### ISSUE TITLE
Issue with manual setup

### ISSUE THREAD

**Issue by xerta555** [jeroentvb/spicetify-power-bar#42] opened 2023-08-03 13:10 UTC
**Describe the bug**
When i do a manual install of the extension as described in the `Readme.md` file, i do theses commands:

`spicetify config extensions power-bar.js`
`spicetify apply enable-devtools`

There is my console log of Spotify:
![image](https://github.com/jeroentvb/spicetify-power-bar/assets/20888017/e0742dc7-9541-4331-a2e0-d99b442d2c27)

The extension isn't active in Spotify.

If i do:
`spicetify config extensions power-bar.js-`
`spicetify apply enable-devtools`

And i install the extension through the Spicetify Marketplace with a reload, it works, the extension is enabled.

**Device info (please complete the following information):**
 - OS: Windows 10
 - Spicetify version: v2.22.1
 - Spotify version: 1.2.17.832.g15fa351e

**Comment by jeroentvb** [comment] 2023-08-07 19:15
This issue was caused by React not being available when the app was launched, but apparently injecting extensions via the marketplace has enough delay for React to be available on launch.
The issue was fixed in https://github.com/spicetify/spicetify-creator/pull/15, so power-bar simply needed the updated spicetify-creator.

**Comment by xerta555** [comment] 2023-08-07 19:33
> This issue was caused by React not being available when the app was launched, but apparently injecting extensions via the marketplace has enough delay for React to be available on launch. The issue was fixed in [spicetify/spicetify-creator#15](https://github.com/spicetify/spicetify-creator/pull/15), so power-bar simply needed the updated spicetify-creator.

Ah ok i understand now.
Thx for explanation.

So now the Spicetify extensions creator have to update their extensions, right ?

**Comment by jeroentvb** [comment] 2023-08-07 19:35
All apps and extensions built with spicetify-creator will need to create a new build using the latest version of spicetify creator to be compatible with the latest spotify version.

**Comment by xerta555** [comment] 2023-08-07 20:46
Just test your last version and i get theses errors
![image](https://github.com/jeroentvb/spicetify-power-bar/assets/20888017/58bad272-6598-4d58-8b77-774b7fcd19f0)

Is it come from the extension or something other ?

**Closed** 2023-08-09 16:03 UTC
Labels: bug

**Comment by jeroentvb** [comment] 2023-08-09 16:05
I did an oopsie. Power-bar is working again 😅

**Comment by xerta555** [comment] 2023-08-09 21:40
I confirm, it works again.

Nice job, thx for this update 👍🏻 

Have a nice day
